module Appium
  def self.symbolize_keys: (Hash[untyped, untyped] hash, ?nested: bool, ?enable_deprecation_msg: bool)
    -> Hash[Symbol, untyped]

  module Core
    def self.for: (*untyped args) -> Driver
  end
end
