module Faye
  module WebSocket
    class Client
      def initialize: (String, String, Hash[Symbol, untyped]) -> void
      def close: () -> void
      def send: (String) -> void
      def on: (String, Proc) -> void
    end
  end
end