AllCops:
  TargetRubyVersion: 2.4
Metrics/LineLength:
  Max: 128
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 14
Metrics/PerceivedComplexity:
  Max: 14
Metrics/ParameterLists:
  Enabled: false
Lint/NestedMethodDefinition:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/UnpackFirst:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: true
  Exclude:
    - test/**/*
Naming/RescuedExceptionsVariableName:
  Enabled: false
Layout/RescueEnsureAlignment:
  Enabled: false
