# frozen_string_literal: true

module Appium
  module Core
    module Android
      module Uiautomator2
        module Device
          extend Forwardable

          def self.extended: (untyped _mod) -> void
        end
      end
    end
  end
end
