module Appium
  module Core
    module Android
      module Device
        extend Forwardable

        def self.execute: (Symbol command, ?Hash[untyped, untyped], ?Hash[untyped, untyped]) -> untyped

        def self.extended: (untyped _mod) -> (nil | untyped)
      end
    end
  end
end
