module Appium
  module Core
    class Base
      module Device
        module Context
          def within_context: (untyped context) ?{ () -> untyped } -> untyped

          def current_context: () -> untyped

          def available_contexts: () -> untyped

          def set_context: (?untyped? context) -> untyped
        end
      end
    end
  end
end
