module Appium
  module Core
    class Base
      module Device
        module DeviceLock
          include _Bridge

          def lock: (?untyped? duration) -> untyped

          def device_locked?: () -> untyped

          def unlock: () -> untyped
        end
      end
    end
  end
end
