module Appium
  module Core
    class Base
      module Device
        module Device
          include _Bridge

          def shake: () -> untyped

          def device_time: (?untyped? format) -> untyped
        end
      end
    end
  end
end
