module Appium
  module Core
    class Base
      module Device
        module FileManagement
          def push_file: (untyped path, untyped filedata) -> untyped

          def pull_file: (untyped path) -> untyped

          def pull_folder: (untyped path) -> untyped
        end
      end
    end
  end
end
