module Appium
  module Core
    class Base
      module Device
        module Keyboard
          include _Bridge

          def hide_keyboard: (?untyped? close_key, ?untyped? strategy) -> untyped

          def is_keyboard_shown: () -> untyped
        end
      end
    end
  end
end
