module Appium
  module Core
    class Base
      module Device
        module Orientation
          def screen_orientation=: (untyped orientation) -> untyped

          def screen_orientation: () -> untyped
        end
      end
    end
  end
end
