module Appium
  module Core
    class Base
      module Device
        class ScreenRecord
          @upload_option: untyped

          attr_reader upload_option: untyped

          METHOD: ::Array["POST" | "PUT"]

          def initialize: (?remote_path: untyped?, ?user: untyped?, ?pass: untyped?, ?method: ::String, ?file_field_name: untyped?, ?form_fields: untyped?, ?headers: untyped?, ?force_restart: untyped?) -> void

          module Command
            def stop_recording_screen: (?remote_path: untyped?, ?user: untyped?, ?pass: untyped?, ?method: ::String, ?file_field_name: untyped?, ?form_fields: untyped?, ?headers: untyped?) -> untyped

            def stop_and_save_recording_screen: (untyped file_path) -> untyped
          end
        end
      end
    end
  end
end
