module Appium
  module Core
    class Base
      module Device
        module Setting
          def execute: (Symbol command, ?Hash[untyped, untyped], ?Hash[untyped, untyped]) -> untyped

          def get_settings: () -> untyped

          def update_settings: (untyped settings) -> untyped
        end
      end
    end
  end
end
