module Appium
  module Core
    module Android
      module Device
        module Clipboard
          include _Bridge

          def self.add_methods: () -> untyped
        end
      end
    end
  end
end
