module Appium
  module Core
    class Base
      module HasNetworkConnection
        def network_connection_type: () -> untyped

        def network_connection_type=: (untyped connection_type) -> untyped

        private

        def type_to_values: () -> Hash[Symbol, Integer]

        def values_to_type: () -> untyped

        def valid_type?: (untyped type) -> untyped
      end
    end
  end
end
