module Appium
  module Core
    class Base
      module Rotatable
        ORIENTATIONS: Array[Symbol]

        # Expects including class to have bridge accessor
        def bridge: () -> untyped

        def rotation=: (untyped orientation) -> untyped

        alias rotate rotation=

        alias orientation= rotation=

        def orientation: () -> untyped
      end
    end
  end
end
