# jobs for functional test
parameters:
  vmImage: 'macOS-12'
  vmImageForIOS: 'macOS-12'
  androidSDK: 29  # API Level 30 emulators are more unstable than 29
  appiumVersion: '2'  # for appium 2 upstream
  ignoreVersionSkip: true
  CI: true

jobs:
  - job: func_test_android_opencv
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: ${{ parameters.ci }}
      ANDROID_SDK_VERSION: ${{ parameters.androidSDK }}
      IGNORE_VERSION_SKIP: ${{ parameters.ignoreVersionSkip }}
      APPIUM_VERSION: ${{ parameters.appiumVersion }}
    strategy:
      matrix:
        uiautomator2:
          APPIUM_DRIVER: uiautomator2
        espresso:
          APPIUM_DRIVER: espresso
    steps:
      - template: ./functional/android_setup.yml
      - template: ./functional/run_appium.yml
      - script: bundle exec rake test:func:android TESTS=test/functional/android/android/image_comparison_test.rb,test/functional/android/android/mjpeg_server_test.rb
        displayName: Run tests func_test_android_opencv
      - template: ./functional/publish_test_result.yml
