# jobs for functional test
parameters:
  vmImage: 'macOS-12'
  vmImageForIOS: 'macOS-12'
  androidSDK: 29  # API Level 30 emulators are more unstable than 29
  appiumVersion: '2'  # for appium 2 upstream
  ignoreVersionSkip: true
  CI: true

jobs:
  - job: func_test_android_base
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: ${{ parameters.ci }}
      ANDROID_SDK_VERSION: ${{ parameters.androidSDK }}
      IGNORE_VERSION_SKIP: ${{ parameters.ignoreVersionSkip }}
      APPIUM_VERSION: ${{ parameters.appiumVersion }}
    strategy:
      matrix:
        uiautomator2:
          APPIUM_DRIVER: uiautomator2
        espresso:
          APPIUM_DRIVER: espresso
    steps:
    - template: ./functional/android_setup.yml
    - template: ./functional/run_appium.yml
    - script: bundle exec rake test:func:android TESTS=test/functional/android/driver_test.rb,test/functional/android/patch_test.rb
      displayName: Run tests func_test_android_base
    - template: ./functional/publish_test_result.yml

  - job: func_test_android_webdriver
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: ${{ parameters.ci }}
      ANDROID_SDK_VERSION: ${{ parameters.androidSDK }}
      IGNORE_VERSION_SKIP: ${{ parameters.ignoreVersionSkip }}
      APPIUM_VERSION: ${{ parameters.appiumVersion }}
    strategy:
      matrix:
        uiautomator2:
          APPIUM_DRIVER: uiautomator2
        espresso:
          APPIUM_DRIVER: espresso
    steps:
      - template: ./functional/android_setup.yml
      - template: ./functional/run_appium.yml
      - script: bundle exec rake test:func:android TESTS=test/functional/android/webdriver/create_session_test.rb,test/functional/android/webdriver/device_test.rb,test/functional/android/webdriver/w3c_actions_test.rb
        displayName: Run tests func_test_android_webdriver
      - template: ./functional/publish_test_result.yml

  - job: func_test_android_android1
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: ${{ parameters.ci }}
      ANDROID_SDK_VERSION: ${{ parameters.androidSDK }}
      IGNORE_VERSION_SKIP: ${{ parameters.ignoreVersionSkip }}
      APPIUM_VERSION: ${{ parameters.appiumVersion }}
    strategy:
      matrix:
        uiautomator2:
          APPIUM_DRIVER: uiautomator2
        espresso:
          APPIUM_DRIVER: espresso
    steps:
      - template: ./functional/android_setup.yml
      - template: ./functional/run_appium.yml
      - script: bundle exec rake test:func:android TESTS=test/functional/android/android/device_test.rb
        displayName: Run tests func_test_android_android1
      - template: ./functional/publish_test_result.yml

  - job: func_test_android_android2
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: ${{ parameters.ci }}
      ANDROID_SDK_VERSION: ${{ parameters.androidSDK }}
      IGNORE_VERSION_SKIP: ${{ parameters.ignoreVersionSkip }}
      APPIUM_VERSION: ${{ parameters.appiumVersion }}
    strategy:
      matrix:
        uiautomator2:
          APPIUM_DRIVER: uiautomator2
        espresso:
          APPIUM_DRIVER: espresso
    steps:
      - template: ./functional/android_setup.yml
      - template: ./functional/run_appium.yml
      - script: bundle exec rake test:func:android TESTS=test/functional/android/android/search_context_test.rb,test/functional/android/android/mjpeg_server_test.rb
        displayName: Run tests func_test_android_android2
      - template: ./functional/publish_test_result.yml

  - job: func_test_android_android3
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: ${{ parameters.ci }}
      ANDROID_SDK_VERSION: ${{ parameters.androidSDK }}
      IGNORE_VERSION_SKIP: ${{ parameters.ignoreVersionSkip }}
      APPIUM_VERSION: ${{ parameters.appiumVersion }}
    strategy:
      matrix:
        uiautomator2:
          APPIUM_DRIVER: uiautomator2
        espresso:
          APPIUM_DRIVER: espresso
    steps:
      - template: ./functional/android_setup.yml
      - template: ./functional/run_appium.yml
      - script: bundle exec rake test:func:android TESTS=test/functional/android/android/device_data_test.rb
        displayName: Run tests func_test_android_android3
      - template: ./functional/publish_test_result.yml

  - job: func_test_android_mobile_command_espresso
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: ${{ parameters.ci }}
      ANDROID_SDK_VERSION: ${{ parameters.androidSDK }}
      IGNORE_VERSION_SKIP: ${{ parameters.ignoreVersionSkip }}
      APPIUM_VERSION: ${{ parameters.appiumVersion }}
    strategy:
      matrix:
        uiautomator2:
          APPIUM_DRIVER: uiautomator2
        espresso:
          APPIUM_DRIVER: espresso
    steps:
      - template: ./functional/android_setup.yml
      - template: ./functional/run_appium.yml
      - script: bundle exec rake test:func:android TESTS=test/functional/android/android/mobile_commands_test.rb
        displayName: Run tests func_test_android_mobile_command_espresso
      - template: ./functional/publish_test_result.yml

  - job: func_test_android_opencv
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: ${{ parameters.ci }}
      ANDROID_SDK_VERSION: ${{ parameters.androidSDK }}
      IGNORE_VERSION_SKIP: ${{ parameters.ignoreVersionSkip }}
      APPIUM_VERSION: ${{ parameters.appiumVersion }}
    strategy:
      matrix:
        uiautomator2:
          APPIUM_DRIVER: uiautomator2
        espresso:
          APPIUM_DRIVER: espresso
    steps:
      - template: ./functional/android_setup.yml
      - template: ./functional/run_appium.yml
      - script: bundle exec rake test:func:android TESTS=test/functional/android/android/image_comparison_test.rb
        displayName: Run tests func_test_android_opencv
      - template: ./functional/publish_test_result.yml
