# jobs for functional test
parameters:
  vmImage: 'macOS-10.14'

jobs:
  # Run unit tests on different Node versions
  - job: func_test_ios_base
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: true
    steps:
    - template: ./functional/ios_setup.yml
      parameters:
        xcodeVersion: 10.1
    - template: ./functional/run_appium.yml
    - script: bundle exec rake test:func:ios TESTS=test/functional/ios/driver_test.rb,test/functional/ios/patch_test.rb
      displayName: Run tests
    - template: ./functional/publish_test_result.yml
      parameters:
        xcodeVersion: 'Run_func_test_on_iOS'

  - job: func_test_ios_webdriver1
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: true
    steps:
    - template: ./functional/ios_setup.yml
      parameters:
        xcodeVersion: 10.1
    - template: ./functional/run_appium.yml
    - script: bundle exec rake test:func:ios TESTS=test/functional/ios/webdriver/create_session_test.rb,test/functional/ios/webdriver/w3c_actions_test.rb
      displayName: Run tests
    - template: ./functional/publish_test_result.yml
      parameters:
        xcodeVersion: 'Run_func_test_on_iOS_webdriver1'

  - job: func_test_ios_webdriver2
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: true
    steps:
    - template: ./functional/ios_setup.yml
      parameters:
        xcodeVersion: 10.1
    - template: ./functional/run_appium.yml
    - script: bundle exec rake test:func:ios TESTS=test/functional/ios/webdriver/device_test.rb
      displayName: Run tests
    - template: ./functional/publish_test_result.yml
      parameters:
        xcodeVersion: 'Run_func_test_on_iOS_webdriver2'

  - job: func_test_ios_ios1
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: true
    steps:
    - template: ./functional/ios_setup.yml
      parameters:
        xcodeVersion: 10.1
    - template: ./functional/run_appium.yml
    - script: bundle exec rake test:func:ios TESTS=test/functional/ios/ios/device_test.rb
      displayName: Run tests
    - template: ./functional/publish_test_result.yml
      parameters:
        xcodeVersion: 'Run_func_test_on_iOS_ios1'

  - job: func_test_ios_ios2
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: true
    steps:
    - template: ./functional/ios_setup.yml
      parameters:
        xcodeVersion: 10.1
    - template: ./functional/run_appium.yml
    - script: bundle exec rake test:func:ios TESTS=test/functional/ios/ios/device_wda_attachment_test.rb,test/functional/ios/ios/image_comparison_test.rb
      displayName: Run tests
    - template: ./functional/publish_test_result.yml
      parameters:
        xcodeVersion: 'Run_func_test_on_iOS_ios2'

  - job: func_test_ios_ios3
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: true
    steps:
    - template: ./functional/ios_setup.yml
      parameters:
        xcodeVersion: 10.1
    - script: brew install ffmpeg && brew tap wix/brew && brew install wix/brew/applesimutils
      displayName: Install ffmpeg and applesimutils
    - template: ./functional/run_appium.yml
    - script: bundle exec rake test:func:ios TESTS=test/functional/ios/ios/mjpeg_server_test.rb,test/functional/ios/ios/mobile_commands_test.rb,test/functional/ios/ios/search_context_test.rb
      displayName: Run tests
    - template: ./functional/publish_test_result.yml
      parameters:
        xcodeVersion: 'Run_func_test_on_iOS_ios3'

  - job: func_test_ios_tvos
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: true
    steps:
    - template: ./functional/ios_setup.yml
      parameters:
        xcodeVersion: 10.2
    - template: ./functional/run_appium.yml
    - script: bundle exec rake test:func:ios TESTS=test/functional/ios/tv_driver_test.rb
      displayName: Run tests
    - template: ./functional/publish_test_result.yml
      parameters:
        xcodeVersion: 'Run_func_test_on_iOS_tv'

  - job: func_test_android_base
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: true
      ANDROID_SDK_VERSION: 28
    steps:
    - template: ./functional/android_setup.yml
    - template: ./functional/run_appium.yml
    - script: bundle exec rake test:func:android TESTS=test/functional/android/driver_test.rb,test/functional/android/patch_test.rb
      displayName: Run tests
    - template: ./functional/publish_test_result.yml
      parameters:
        xcodeVersion: 'Run_func_test_on_android_base'

  - job: func_test_android_webdriver
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: true
      ANDROID_SDK_VERSION: 28
    steps:
      - template: ./functional/android_setup.yml
      - template: ./functional/run_appium.yml
      - script: bundle exec rake test:func:android TESTS=test/functional/android/webdriver/create_session_test.rb,test/functional/android/webdriver/device_test.rb,test/functional/android/webdriver/w3c_actions_test.rb
        displayName: Run tests
      - template: ./functional/publish_test_result.yml
        parameters:
          xcodeVersion: 'Run_func_test_on_android_base'

  - job: func_test_android_android1
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: true
      ANDROID_SDK_VERSION: 28
    steps:
      - template: ./functional/android_setup.yml
      - template: ./functional/run_appium.yml
      - script: bundle exec rake test:func:android TESTS=test/functional/android/android/device_test.rb
        displayName: Run test/functional/android/android/device_test.rb
      - template: ./functional/publish_test_result.yml
        parameters:
          xcodeVersion: 'func_test_android_android1'

  - job: func_test_android_android2
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: true
      ANDROID_SDK_VERSION: 28
    steps:
      - template: ./functional/android_setup.yml
      - template: ./functional/run_appium.yml
      - script: bundle exec rake test:func:android TESTS=test/functional/android/android/image_comparison_test.rb,test/functional/android/android/mjpeg_server_test.rb
        displayName: Run tests
      - template: ./functional/publish_test_result.yml
        parameters:
          xcodeVersion: 'func_test_android_android2'

  - job: func_test_android_android3
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: true
      ANDROID_SDK_VERSION: 28
    steps:
      - template: ./functional/android_setup.yml
      - template: ./functional/run_appium.yml
      - script: bundle exec rake test:func:android TESTS=test/functional/android/android/mobile_commands_test.rb,test/functional/android/android/search_context_test.rb
        displayName: Run tests
      - template: ./functional/publish_test_result.yml
        parameters:
          xcodeVersion: 'func_test_android_android3'

  - job: func_test_android_android4
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: true
      ANDROID_SDK_VERSION: 28
    steps:
      - template: ./functional/android_setup.yml
      - template: ./functional/run_appium.yml
      - script: bundle exec rake test:func:android TESTS=test/functional/android/android/device_data_test.rb
        displayName: Run tests
      - template: ./functional/publish_test_result.yml
        parameters:
          xcodeVersion: 'func_test_android_android4'

  - job: func_test_android_mobile_command_espresso
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: true
      ANDROID_SDK_VERSION: 28
      AUTOMATION_NAME_DROID: espresso
    steps:
      - template: ./functional/android_setup.yml
      - template: ./functional/run_appium.yml
      - script: bundle exec rake test:func:android TESTS=test/functional/android/android/mobile_commands_test.rb
        displayName: Run tests
      - template: ./functional/publish_test_result.yml
        parameters:
          xcodeVersion: 'func_test_android_mobile_command_espresso'
