module Appium
  module Core
    # Element class inheriting from Selenium::WebDriver::Element
    class Element < ::Selenium::WebDriver::Element
      include ::Appium::Core::Base::TakesScreenshot

      def initialize: (untyped bridge, untyped id) -> void

      attr_reader id: Array[untyped]

      def method_missing: (untyped method_name, *untyped args) { (?) -> untyped } -> (nil | untyped)

      def respond_to_missing?: (untyped _method_name, bool _include_private) -> true

      # Alias for type
      alias type send_keys

      def location_rel: (untyped driver) -> untyped

      def screenshot: () -> untyped

      def screenshot_as: (untyped format) -> untyped

      def save_screenshot: (untyped png_path) -> untyped
    end
  end
end
